/**
 * @file SystemState.hpp
 * @brief Thread-safe centralized state manager for semantic rover intent commands.
 *
 * Synchronizes access to the shared RoverIntentCommand state across the hardware polling,
 * input mapping, and asynchronous UDP transmission threads.
 */
#pragma once
#include <mutex>
#include "DTO/Command.hpp"

class SystemState
{
public:
    SystemState();

    /**
     * @brief Updates the centralized semantic rover command state.
     * @param cmd The new RoverIntentCommand DTO generated by the Command Dispatcher.
     */
    void set_rover_command(const RoverIntentCommand &cmd);

    /**
     * @brief Retrieves a thread-safe copy of the current rover command.
     * @return A copy of the current RoverIntentCommand.
     */
    RoverIntentCommand get_rover_command() const;

private:
    RoverIntentCommand current_cmd;
    mutable std::mutex state_mutex;
};